#include "../../linear_algebra.h"


void multiply_matrix_by_scalar(TYPE* mat_a, int rows, int cols, TYPE scalar, TYPE* mat_c) {

  /*@ begin PerfTuning (

    def build {
      arg build_command = 'icc';
      #arg libs = '-lrt';  # Only needed on linux
    } 

    def performance_counter {
      arg repetitions = 50;
    }

    def performance_params {  
      param U_I[] = range(1,6);
      param U_J[] = range(1,6);

      param RT1_I[] = [1,2,6];
      param RT1_J[] = [1,2,6];

      param VEC[] = [False,True];

      param CFLAGS[] = ['-O1', '-O2', '-O3'];
      constraint unroll_limit = ((U_I == 1) or (U_J == 1));
      constraint reg_capacity_1 = (RT1_I*RT1_J <= 150);

    }

    def input_params {
      let N = [6];
      param rows[] = N;
      param cols[] = N;
    }

    def input_vars {
      decl dynamic double mat_a[rows*cols] = random;
      decl dynamic double mat_b[rows*cols] = random;
      decl dynamic double mat_c[rows*cols] = 0;
      decl double scalar = random;
    }

    def search {
      arg algorithm = 'Exhaustive';
    }

  ) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [1.196e-06, 2.8e-07, 1.86e-07, 1.83e-07, 1.81e-07, 1.83e-07, 1.83e-07, 1.82e-07, 1.82e-07, 1.82e-07, 1.82e-07, 1.8e-07, 1.81e-07, 1.82e-07, 1.8e-07, 1.8e-07, 1.82e-07, 1.81e-07, 1.81e-07, 1.8e-07, 1.79e-07, 1.83e-07, 1.81e-07, 1.82e-07, 1.82e-07, 1.81e-07, 1.83e-07, 1.8e-07, 1.83e-07, 1.81e-07, 1.83e-07, 1.82e-07, 1.81e-07, 1.8e-07, 1.82e-07, 1.81e-07, 1.81e-07, 1.81e-07, 1.82e-07, 1.81e-07, 1.8e-07, 1.8e-07, 1.81e-07, 1.8e-07, 1.82e-07, 1.82e-07, 1.82e-07, 1.8e-07, 1.81e-07, 1.82e-07] 
Tuned for specific problem sizes: 
  cols = 6 
  rows = 6 
Best performance parameters: 
  CFLAGS = -O3 
  RT1_I = 6 
  RT1_J = 1 
  U_I = 3 
  U_J = 1 
  VEC = True 
--**/


    
  int i, j, it, jt;
  int ind, row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I,U_J]),
      regtile = (['i','j'],[RT1_I,RT1_J]),
      vector = (VEC, ['ivdep','vector always'])
    )
    for (i = 0; i <= rows-1; i++) {
      for (j = 0; j <= cols-1; j++) {
        mat_c[cols * i + j] = mat_a[cols * i + j] * scalar;
      }
    }
  ) @*/
  {
    for (it=0; it<=rows-6; it=it+6) {
      register int cbv_1;
      cbv_1=cols-1;
#pragma ivdep
#pragma vector always
      for (j=0; j<=cbv_1; j++ ) {
        mat_c[cols*it+j]=mat_a[cols*it+j]*scalar;
        mat_c[cols*(it+1)+j]=mat_a[cols*(it+1)+j]*scalar;
        mat_c[cols*(it+2)+j]=mat_a[cols*(it+2)+j]*scalar;
        mat_c[cols*(it+3)+j]=mat_a[cols*(it+3)+j]*scalar;
        mat_c[cols*(it+4)+j]=mat_a[cols*(it+4)+j]*scalar;
        mat_c[cols*(it+5)+j]=mat_a[cols*(it+5)+j]*scalar;
      }
    }
    {
      int i;
      for (i=it; i<=rows-3; i=i+3) {
        register int cbv_2;
        cbv_2=cols-1;
#pragma ivdep
#pragma vector always
        for (j=0; j<=cbv_2; j++ ) {
          mat_c[cols*i+j]=mat_a[cols*i+j]*scalar;
          mat_c[cols*(i+1)+j]=mat_a[cols*(i+1)+j]*scalar;
          mat_c[cols*(i+2)+j]=mat_a[cols*(i+2)+j]*scalar;
        }
      }
      for (i=rows-((rows-(it))%3); i<=rows-1; i=i+1) {
        register int cbv_3;
        cbv_3=cols-1;
#pragma ivdep
#pragma vector always
        for (j=0; j<=cbv_3; j++ ) {
          mat_c[cols*i+j]=mat_a[cols*i+j]*scalar;
        }
      }
    }
  }
/*@ end @*/
/*@ end @*/

  
}
