#include "../../linear_algebra.h"

void add_matrix(TYPE* mat_a, int rows, int cols, TYPE* mat_b, TYPE* mat_c)  {

/*@ begin PerfTuning (

 def build {
   arg build_command = 'icc';
   #arg libs = '-lrt';  # Only needed on linux
 } 

 def performance_counter {
   arg repetitions = 5;
 }

 def performance_params {  
  param U_I[] = range(1,6);
  param U_J[] = range(1,6);

  param RT1_I[] = [1,2,6];
  param RT1_J[] = [1,2,6];

  param VEC[] = [False,True];

  param CFLAGS[] = ['-O1', '-O2', '-O3'];
  constraint unroll_limit = ((U_I == 1) or (U_J == 1));

  constraint reg_capacity_1 = (RT1_I*RT1_J <= 150);
 }
 
 def input_params {
  let N = [6];
  param rows[] = N;
  param cols[] = N;
 }
 
 def input_vars {
   decl dynamic double mat_a[rows*cols] = random;
   decl dynamic double mat_b[rows*cols] = random;
   decl dynamic double mat_c[rows*cols] = 0;
 }
 
 def search {
   arg algorithm = 'Exhaustive';
 }

) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [5.7e-07, 1.6e-07, 1.23e-07, 1.23e-07, 1.24e-07] 
Tuned for specific problem sizes: 
  cols = 6 
  rows = 6 
Best performance parameters: 
  CFLAGS = -O2 
  RT1_I = 1 
  RT1_J = 1 
  U_I = 1 
  U_J = 4 
  VEC = True 
--**/


int i, j;
int it, jt;

/*@ begin Loop (  
  transform Composite(
    unrolljam = (['i','j'],[U_I,U_J]),
    vector = (VEC, ['ivdep','vector always']),
    regtile = (['i','j'],[RT1_I,RT1_J])
)
  for (i = 0; i <= rows-1; i++) {
    for (j = 0; j <= cols-1; j++) {
      mat_c[ cols * i + j] = mat_a[ cols * i + j] + mat_b[ cols * i + j];
    }
  }
) @*/
for (i=0; i<=rows-1; i++ ) {
  {
    int j;
    register int cbv_1;
    cbv_1=cols-4;
#pragma ivdep
#pragma vector always
    for (j=0; j<=cbv_1; j=j+4) {
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
      mat_c[cols*i+j+1]=mat_a[cols*i+j+1]+mat_b[cols*i+j+1];
      mat_c[cols*i+j+2]=mat_a[cols*i+j+2]+mat_b[cols*i+j+2];
      mat_c[cols*i+j+3]=mat_a[cols*i+j+3]+mat_b[cols*i+j+3];
    }
    register int cbv_2, cbv_3;
    cbv_2=cols-((cols-(0))%4);
    cbv_3=cols-1;
#pragma ivdep
#pragma vector always
    for (j=cbv_2; j<=cbv_3; j=j+1) 
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
  }
}
/*@ end @*/
/*@ end @*/

}