#include "../../linear_algebra.h"

void add_matrix(KALMAN_TYPE* mat_a, int rows, int cols, KALMAN_TYPE* mat_b, KALMAN_TYPE* mat_c)  {
 
#ifdef USE_CALI
CALI_CXX_MARK_FUNCTION;
#endif
/*@ begin PerfTuning (

 def build {
   arg build_command = 'icc';
   #arg libs = '-lrt';  # Only needed on linux
 } 

 def performance_counter {
   arg repetitions = 50;
 }

 def performance_params {  
  param U_I[] = range(1,6);
  param U_J[] = range(1,6);

  param RT1_I[] = [1,2,6];
  param RT1_J[] = [1,2,6];

  param VEC[] = [False,True];

  param CFLAGS[] = ['-O1', '-O2', '-O3'];
  constraint unroll_limit = ((U_I == 1) or (U_J == 1));

  constraint reg_capacity_1 = (RT1_I*RT1_J <= 150);
 }
 
 def input_params {
  let N = [6];
  param rows[] = N;
  param cols[] = N;
 }
 
 def input_vars {
   decl dynamic double mat_a[rows*cols] = random;
   decl dynamic double mat_b[rows*cols] = random;
   decl dynamic double mat_c[rows*cols] = 0;
 }
 
 def search {
   arg algorithm = 'Exhaustive';
 }

) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [1.426e-06, 6.57e-07, 5.09e-07, 5.36e-07, 5.05e-07, 5.1e-07, 5.08e-07, 5.07e-07, 5.02e-07, 5.09e-07, 5.07e-07, 5.02e-07, 5.06e-07, 5.03e-07, 5.06e-07, 5.05e-07, 5.04e-07, 5.03e-07, 5.04e-07, 5.05e-07, 5.07e-07, 5.06e-07, 5.03e-07, 5.06e-07, 5.09e-07, 5.11e-07, 5.07e-07, 5.05e-07, 5.08e-07, 5.08e-07, 5.03e-07, 5.06e-07, 5.09e-07, 5.09e-07, 5.06e-07, 4.98e-07, 5.04e-07, 5.07e-07, 5.08e-07, 5.05e-07, 5.08e-07, 5.01e-07, 5.06e-07, 5.02e-07, 5.03e-07, 5.05e-07, 5.03e-07, 5.07e-07, 5.09e-07, 4.99e-07] 
Tuned for specific problem sizes: 
  cols = 6 
  rows = 6 
Best performance parameters: 
  CFLAGS = -O3 
  RT1_I = 6 
  RT1_J = 1 
  U_I = 2 
  U_J = 1 
  VEC = True 
--**/


int i, j;
int it, jt;

/*@ begin Loop (  
  transform Composite(
    unrolljam = (['i','j'],[U_I,U_J]),
    vector = (VEC, ['ivdep','vector always']),
    regtile = (['i','j'],[RT1_I,RT1_J])
)
  for (i = 0; i <= rows-1; i++) {
    for (j = 0; j <= cols-1; j++) {
      mat_c[ cols * i + j] = mat_a[ cols * i + j] + mat_b[ cols * i + j];
    }
  }
) @*/
{
  for (it=0; it<=rows-6; it=it+6) {
    register int cbv_1;
    cbv_1=cols-1;
#pragma ivdep
#pragma vector always
    for (j=0; j<=cbv_1; j++ ) {
      mat_c[cols*it+j]=mat_a[cols*it+j]+mat_b[cols*it+j];
      mat_c[cols*(it+1)+j]=mat_a[cols*(it+1)+j]+mat_b[cols*(it+1)+j];
      mat_c[cols*(it+2)+j]=mat_a[cols*(it+2)+j]+mat_b[cols*(it+2)+j];
      mat_c[cols*(it+3)+j]=mat_a[cols*(it+3)+j]+mat_b[cols*(it+3)+j];
      mat_c[cols*(it+4)+j]=mat_a[cols*(it+4)+j]+mat_b[cols*(it+4)+j];
      mat_c[cols*(it+5)+j]=mat_a[cols*(it+5)+j]+mat_b[cols*(it+5)+j];
    }
  }
  {
    int i;
    for (i=it; i<=rows-2; i=i+2) {
      register int cbv_2;
      cbv_2=cols-1;
#pragma ivdep
#pragma vector always
      for (j=0; j<=cbv_2; j++ ) {
        mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
        mat_c[cols*(i+1)+j]=mat_a[cols*(i+1)+j]+mat_b[cols*(i+1)+j];
      }
    }
    for (i=rows-((rows-(it))%2); i<=rows-1; i=i+1) {
      register int cbv_3;
      cbv_3=cols-1;
#pragma ivdep
#pragma vector always
      for (j=0; j<=cbv_3; j++ ) {
        mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
      }
    }
  }
}
/*@ end @*/
/*@ end @*/

}