#include "../../linear_algebra.h"

void add_matrix(TYPE* mat_a, int rows, int cols, TYPE* mat_b, TYPE* mat_c)  {

/*@ begin PerfTuning (

 def build {
   arg build_command = 'gcc';
   #arg libs = '-lrt';  # Only needed on linux
 } 

 def performance_counter {
   arg repetitions = 5;
 }

 def performance_params {  
  param U_I[] = range(1,31);
  param U_J[] = range(1,31);

  param VEC[] = [False,True];

  param CFLAGS[] = ['-O0', '-O1', '-O2', '-O3'];
  constraint unroll_limit = ((U_I == 1) or (U_J == 1));

 }
 
 def input_params {
  let R = [100];
  let C = [100];
  param rows[] = R;
  param cols[] = C;
 }
 
 def input_vars {
   decl dynamic double mat_a[rows*cols] = random;
   decl dynamic double mat_b[rows*cols] = random;
   decl dynamic double mat_c[rows*cols] = 0;
 }
 
 def search {
   arg algorithm = 'Exhaustive';
 }

) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [4.7508e-05, 4.6957e-05, 4.6492e-05, 4.6436e-05, 4.6383e-05] 
Tuned for specific problem sizes: 
  cols = 100 
  rows = 100 
Best performance parameters: 
  CFLAGS = -O0 
  U_I = 10 
  U_J = 1 
  VEC = True 
--**/


int i, j;

/*@ begin Loop (  
  transform Composite(
    unrolljam = (['i','j'],[U_I,U_J]),
    vector = (VEC, ['ivdep','vector always'])
)
  for (i = 0; i <= rows-1; i++) {
    for (j = 0; j <= cols-1; j++) {
      mat_c[ cols * i + j] = mat_a[ cols * i + j] + mat_b[ cols * i + j];
    }
  }
) @*/
{
  int i;
  for (i=0; i<=rows-10; i=i+10) {
    register int cbv_1;
    cbv_1=cols-1;
#pragma ivdep
#pragma vector always
    for (j=0; j<=cbv_1; j++ ) {
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
      mat_c[cols*(i+1)+j]=mat_a[cols*(i+1)+j]+mat_b[cols*(i+1)+j];
      mat_c[cols*(i+2)+j]=mat_a[cols*(i+2)+j]+mat_b[cols*(i+2)+j];
      mat_c[cols*(i+3)+j]=mat_a[cols*(i+3)+j]+mat_b[cols*(i+3)+j];
      mat_c[cols*(i+4)+j]=mat_a[cols*(i+4)+j]+mat_b[cols*(i+4)+j];
      mat_c[cols*(i+5)+j]=mat_a[cols*(i+5)+j]+mat_b[cols*(i+5)+j];
      mat_c[cols*(i+6)+j]=mat_a[cols*(i+6)+j]+mat_b[cols*(i+6)+j];
      mat_c[cols*(i+7)+j]=mat_a[cols*(i+7)+j]+mat_b[cols*(i+7)+j];
      mat_c[cols*(i+8)+j]=mat_a[cols*(i+8)+j]+mat_b[cols*(i+8)+j];
      mat_c[cols*(i+9)+j]=mat_a[cols*(i+9)+j]+mat_b[cols*(i+9)+j];
    }
  }
  for (i=rows-((rows-(0))%10); i<=rows-1; i=i+1) {
    register int cbv_2;
    cbv_2=cols-1;
#pragma ivdep
#pragma vector always
    for (j=0; j<=cbv_2; j++ ) {
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
    }
  }
}
/*@ end @*/
/*@ end @*/

}