#include "../../linear_algebra.h"

void multiply_matrix(TYPE* mat_a, int rows_a, int cols_a, 
                     TYPE* mat_b, int cols_b, 
                     TYPE* mat_c) {


  /*@ begin PerfTuning (

    def build {
      arg build_command = 'gcc';
      #arg libs = '-lrt';  # Only needed on linux
    } 

    def performance_counter {
      arg repetitions = 50;
    }

    def performance_params {  
      param U_I0[] = range(1,6);
      param U_J0[] = range(1,6);
      param U_I[] = range(1,6);
      param U_J[] = range(1,6);
      param U_K[] = range(1,6);

      param VEC[] = [False,True];

      param RT0_I[] = [1,2,6];
      param RT0_J[] = [1,2,6];
      param RT1_I[] = [1,2,6];
      param RT1_J[] = [1,2,6];
      param RT1_K[] = [1,2,6];

      param CFLAGS[] = ['-O1', '-O2', '-O3'];
      constraint unroll_limit_0 = ((U_I == 1) or (U_J == 1));
      constraint reg_capacity_0 = (RT1_I*RT1_J <= 150);
      constraint unroll_limit = ((U_I == 1) or (U_J == 1) or (U_K == 1));
      constraint reg_capacity_1 = (RT1_I*RT1_J*RT1_K <= 150);

    }

    def input_params {
      let N = [6, 12];
      param rows_a[] = N;
      param cols_a[] = N;
      param cols_b[] = N;
    }

    def input_vars {
      decl dynamic double mat_a[rows_a*cols_a] = random;
      decl dynamic double mat_b[cols_b*cols_b] = random;
      decl dynamic double mat_c[rows_a*cols_b] = 0;
    }

    def search {
      arg algorithm = 'Randomsearch';
      arg total_runs  = 100000;
    }

  ) @*/
  if ((rows_a<=6) && (cols_a<=6) && (cols_b<=6)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [6.63e-06, 6.106e-06, 6.116e-06, 6.338e-06, 6.104e-06, 6.064e-06, 6.044e-06, 6.116e-06, 6.006e-06, 6.244e-06, 6.098e-06, 6.1e-06, 6.15e-06, 6.056e-06, 5.952e-06, 6.092e-06, 6.104e-06, 6.092e-06, 6.166e-06, 6.26e-06, 6.098e-06, 6.144e-06, 6.086e-06, 6.124e-06, 6.086e-06, 5.954e-06, 6.156e-06, 6.032e-06, 6.182e-06, 6.078e-06, 6.122e-06, 6.304e-06, 6.09e-06, 6.132e-06, 6.084e-06, 6.166e-06, 6.014e-06, 5.948e-06, 6.118e-06, 6.026e-06, 6.014e-06, 5.982e-06, 6e-06, 6.008e-06, 6.1e-06, 6.064e-06, 6.182e-06, 6.228e-06, 6.174e-06, 6.204e-06] 
Tuned for specific problem sizes: 
  cols_a = 6 
  cols_b = 6 
  rows_a = 6 
Best performance parameters: 
  CFLAGS = -O3 
  RT0_I = 1 
  RT0_J = 2 
  RT1_I = 1 
  RT1_J = 1 
  RT1_K = 1 
  U_I = 1 
  U_I0 = 4 
  U_J = 1 
  U_J0 = 1 
  U_K = 3 
  VEC = False 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  {
    int i;
    for (i=0; i<=rows_a-4; i=i+4) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[jt+cols_b*i+1]=0;
        mat_c[jt+cols_b*(i+1)]=0;
        mat_c[jt+cols_b*(i+1)+1]=0;
        mat_c[jt+cols_b*(i+2)]=0;
        mat_c[jt+cols_b*(i+2)+1]=0;
        mat_c[jt+cols_b*(i+3)]=0;
        mat_c[jt+cols_b*(i+3)+1]=0;
      }
      for (j=jt; j<=cols_b-1; j=j+1) {
        mat_c[j+cols_b*i]=0;
        mat_c[j+cols_b*(i+1)]=0;
        mat_c[j+cols_b*(i+2)]=0;
        mat_c[j+cols_b*(i+3)]=0;
      }
    }
    for (i=rows_a-((rows_a-(0))%4); i<=rows_a-1; i=i+1) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[(jt+1)+cols_b*i]=0;
      }
      for (j=jt; j<=cols_b-1; j=j+1) {
        mat_c[j+cols_b*i]=0;
      }
    }
  }
  for (i=0; i<=rows_a-1; i++ ) {
    for (j=0; j<=cols_b-1; j++ ) {
      {
        int k;
        for (k=0; k<=cols_a-3; k=k+3) {
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+1]*mat_b[cols_b*(k+1)+j];
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+2]*mat_b[cols_b*(k+2)+j];
        }
        for (k=cols_a-((cols_a-(0))%3); k<=cols_a-1; k=k+1) 
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
      }
    }
  }
/*@ end @*/
} else if ((rows_a<=6) && (cols_a<=6) && (cols_b<=12)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [1.2134e-05, 1.1824e-05, 1.1648e-05, 1.1806e-05, 1.14e-05, 1.16e-05, 1.167e-05, 1.1568e-05, 1.1674e-05, 1.1902e-05, 1.1782e-05, 1.1416e-05, 1.155e-05, 1.1564e-05, 1.1802e-05, 1.145e-05, 1.1616e-05, 1.186e-05, 1.1556e-05, 1.176e-05, 1.1678e-05, 1.2056e-05, 1.153e-05, 1.1644e-05, 1.1508e-05, 1.175e-05, 1.1604e-05, 1.1932e-05, 1.1704e-05, 1.1546e-05, 1.181e-05, 1.1502e-05, 1.1516e-05, 1.1554e-05, 1.1658e-05, 1.161e-05, 1.1542e-05, 1.1988e-05, 1.1674e-05, 1.145e-05, 1.1526e-05, 1.1564e-05, 1.1622e-05, 1.162e-05, 1.1598e-05, 1.1874e-05, 1.1856e-05, 1.163e-05, 1.2054e-05, 1.1478e-05] 
Tuned for specific problem sizes: 
  cols_a = 6 
  cols_b = 12 
  rows_a = 6 
Best performance parameters: 
  CFLAGS = -O3 
  RT0_I = 1 
  RT0_J = 2 
  RT1_I = 1 
  RT1_J = 1 
  RT1_K = 1 
  U_I = 1 
  U_I0 = 4 
  U_J = 1 
  U_J0 = 1 
  U_K = 3 
  VEC = False 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  {
    int i;
    for (i=0; i<=rows_a-4; i=i+4) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[jt+cols_b*i+1]=0;
        mat_c[jt+cols_b*(i+1)]=0;
        mat_c[jt+cols_b*(i+1)+1]=0;
        mat_c[jt+cols_b*(i+2)]=0;
        mat_c[jt+cols_b*(i+2)+1]=0;
        mat_c[jt+cols_b*(i+3)]=0;
        mat_c[jt+cols_b*(i+3)+1]=0;
      }
      for (j=jt; j<=cols_b-1; j=j+1) {
        mat_c[j+cols_b*i]=0;
        mat_c[j+cols_b*(i+1)]=0;
        mat_c[j+cols_b*(i+2)]=0;
        mat_c[j+cols_b*(i+3)]=0;
      }
    }
    for (i=rows_a-((rows_a-(0))%4); i<=rows_a-1; i=i+1) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[(jt+1)+cols_b*i]=0;
      }
      for (j=jt; j<=cols_b-1; j=j+1) {
        mat_c[j+cols_b*i]=0;
      }
    }
  }
  for (i=0; i<=rows_a-1; i++ ) {
    for (j=0; j<=cols_b-1; j++ ) {
      {
        int k;
        for (k=0; k<=cols_a-3; k=k+3) {
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+1]*mat_b[cols_b*(k+1)+j];
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+2]*mat_b[cols_b*(k+2)+j];
        }
        for (k=cols_a-((cols_a-(0))%3); k<=cols_a-1; k=k+1) 
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
      }
    }
  }
/*@ end @*/
} else if ((rows_a<=6) && (cols_a<=12) && (cols_b<=6)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [1.2792e-05, 1.2158e-05, 1.2e-05, 1.2004e-05, 1.1946e-05, 1.1584e-05, 1.1938e-05, 1.1836e-05, 1.2086e-05, 1.1906e-05, 1.194e-05, 1.186e-05, 1.165e-05, 1.1818e-05, 1.1538e-05, 1.1834e-05, 1.2052e-05, 1.2126e-05, 1.1944e-05, 1.2134e-05, 1.1984e-05, 1.2208e-05, 1.2e-05, 1.1768e-05, 1.1898e-05, 1.195e-05, 1.1842e-05, 1.19e-05, 1.1676e-05, 1.1858e-05, 1.2066e-05, 1.1996e-05, 1.1928e-05, 1.1986e-05, 1.1868e-05, 1.1906e-05, 1.2078e-05, 1.197e-05, 1.1986e-05, 1.1762e-05, 1.1974e-05, 1.1732e-05, 1.211e-05, 1.1966e-05, 1.191e-05, 1.2074e-05, 1.19e-05, 1.1924e-05, 1.1832e-05, 1.183e-05] 
Tuned for specific problem sizes: 
  cols_a = 12 
  cols_b = 6 
  rows_a = 6 
Best performance parameters: 
  CFLAGS = -O1 
  RT0_I = 1 
  RT0_J = 2 
  RT1_I = 2 
  RT1_J = 1 
  RT1_K = 2 
  U_I = 2 
  U_I0 = 3 
  U_J = 1 
  U_J0 = 3 
  U_K = 5 
  VEC = True 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  {
    int i;
    for (i=0; i<=rows_a-3; i=i+3) {
      register int cbv_1;
      cbv_1=cols_b-2;
#pragma ivdep
#pragma vector always
      for (jt=0; jt<=cbv_1; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[jt+cols_b*i+1]=0;
        mat_c[jt+cols_b*(i+1)]=0;
        mat_c[jt+cols_b*(i+1)+1]=0;
        mat_c[jt+cols_b*(i+2)]=0;
        mat_c[jt+cols_b*(i+2)+1]=0;
      }
      {
        int j;
        register int cbv_2;
        cbv_2=cols_b-3;
#pragma ivdep
#pragma vector always
        for (j=jt; j<=cbv_2; j=j+3) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*i+1]=0;
          mat_c[j+cols_b*i+2]=0;
        }
        register int cbv_3, cbv_4;
        cbv_3=cols_b-((cols_b-(jt))%3);
        cbv_4=cols_b-1;
#pragma ivdep
#pragma vector always
        for (j=cbv_3; j<=cbv_4; j=j+1) 
          mat_c[j+cols_b*i]=0;
      }
      {
        int j;
        register int cbv_5;
        cbv_5=cols_b-3;
#pragma ivdep
#pragma vector always
        for (j=jt; j<=cbv_5; j=j+3) {
          mat_c[j+cols_b*(i+1)]=0;
          mat_c[j+cols_b*(i+1)+1]=0;
          mat_c[j+cols_b*(i+1)+2]=0;
        }
        register int cbv_6, cbv_7;
        cbv_6=cols_b-((cols_b-(jt))%3);
        cbv_7=cols_b-1;
#pragma ivdep
#pragma vector always
        for (j=cbv_6; j<=cbv_7; j=j+1) 
          mat_c[j+cols_b*(i+1)]=0;
      }
      {
        int j;
        register int cbv_8;
        cbv_8=cols_b-3;
#pragma ivdep
#pragma vector always
        for (j=jt; j<=cbv_8; j=j+3) {
          mat_c[j+cols_b*(i+2)]=0;
          mat_c[j+cols_b*(i+2)+1]=0;
          mat_c[j+cols_b*(i+2)+2]=0;
        }
        register int cbv_9, cbv_10;
        cbv_9=cols_b-((cols_b-(jt))%3);
        cbv_10=cols_b-1;
#pragma ivdep
#pragma vector always
        for (j=cbv_9; j<=cbv_10; j=j+1) 
          mat_c[j+cols_b*(i+2)]=0;
      }
    }
    for (i=rows_a-((rows_a-(0))%3); i<=rows_a-1; i=i+1) {
      register int cbv_11;
      cbv_11=cols_b-2;
#pragma ivdep
#pragma vector always
      for (jt=0; jt<=cbv_11; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[(jt+1)+cols_b*i]=0;
      }
      {
        int j;
        register int cbv_12;
        cbv_12=cols_b-3;
#pragma ivdep
#pragma vector always
        for (j=jt; j<=cbv_12; j=j+3) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*i+1]=0;
          mat_c[j+cols_b*i+2]=0;
        }
        register int cbv_13, cbv_14;
        cbv_13=cols_b-((cols_b-(jt))%3);
        cbv_14=cols_b-1;
#pragma ivdep
#pragma vector always
        for (j=cbv_13; j<=cbv_14; j=j+1) 
          mat_c[j+cols_b*i]=0;
      }
    }
  }
  {
    for (it=0; it<=rows_a-2; it=it+2) {
      for (j=0; j<=cols_b-1; j++ ) {
        register int cbv_1;
        cbv_1=cols_a-2;
#pragma ivdep
#pragma vector always
        for (kt=0; kt<=cbv_1; kt=kt+2) {
          mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+kt]*mat_b[cols_b*kt+j];
          mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+(kt+1)]*mat_b[cols_b*(kt+1)+j];
          mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+kt]*mat_b[cols_b*kt+j];
          mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+(kt+1)]*mat_b[cols_b*(kt+1)+j];
        }
        {
          int k;
          register int cbv_2;
          cbv_2=cols_a-5;
#pragma ivdep
#pragma vector always
          for (k=kt; k<=cbv_2; k=k+5) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k+1]*mat_b[cols_b*(k+1)+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k+1]*mat_b[cols_b*(k+1)+j];
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k+2]*mat_b[cols_b*(k+2)+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k+2]*mat_b[cols_b*(k+2)+j];
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k+3]*mat_b[cols_b*(k+3)+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k+3]*mat_b[cols_b*(k+3)+j];
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k+4]*mat_b[cols_b*(k+4)+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k+4]*mat_b[cols_b*(k+4)+j];
          }
          register int cbv_3, cbv_4;
          cbv_3=cols_a-((cols_a-(kt))%5);
          cbv_4=cols_a-1;
#pragma ivdep
#pragma vector always
          for (k=cbv_3; k<=cbv_4; k=k+1) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
          }
        }
      }
    }
    {
      int i;
      for (i=it; i<=rows_a-2; i=i+2) {
        for (j=0; j<=cols_b-1; j++ ) {
          register int cbv_5;
          cbv_5=cols_a-2;
#pragma ivdep
#pragma vector always
          for (kt=0; kt<=cbv_5; kt=kt+2) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+kt]*mat_b[cols_b*kt+j];
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+kt+1]*mat_b[cols_b*(kt+1)+j];
            mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+kt]*mat_b[cols_b*kt+j];
            mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+kt+1]*mat_b[cols_b*(kt+1)+j];
          }
          {
            int k;
            register int cbv_6;
            cbv_6=cols_a-5;
#pragma ivdep
#pragma vector always
            for (k=kt; k<=cbv_6; k=k+5) {
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+1]*mat_b[cols_b*(k+1)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+2]*mat_b[cols_b*(k+2)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+3]*mat_b[cols_b*(k+3)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+4]*mat_b[cols_b*(k+4)+j];
            }
            register int cbv_7, cbv_8;
            cbv_7=cols_a-((cols_a-(kt))%5);
            cbv_8=cols_a-1;
#pragma ivdep
#pragma vector always
            for (k=cbv_7; k<=cbv_8; k=k+1) 
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          }
          {
            int k;
            register int cbv_9;
            cbv_9=cols_a-5;
#pragma ivdep
#pragma vector always
            for (k=kt; k<=cbv_9; k=k+5) {
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j];
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k+1]*mat_b[cols_b*(k+1)+j];
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k+2]*mat_b[cols_b*(k+2)+j];
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k+3]*mat_b[cols_b*(k+3)+j];
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k+4]*mat_b[cols_b*(k+4)+j];
            }
            register int cbv_10, cbv_11;
            cbv_10=cols_a-((cols_a-(kt))%5);
            cbv_11=cols_a-1;
#pragma ivdep
#pragma vector always
            for (k=cbv_10; k<=cbv_11; k=k+1) 
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j];
          }
        }
      }
      for (i=rows_a-((rows_a-(it))%2); i<=rows_a-1; i=i+1) 
        for (j=0; j<=cols_b-1; j++ ) {
          register int cbv_12;
          cbv_12=cols_a-2;
#pragma ivdep
#pragma vector always
          for (kt=0; kt<=cbv_12; kt=kt+2) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+kt]*mat_b[cols_b*kt+j];
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+(kt+1)]*mat_b[cols_b*(kt+1)+j];
          }
          {
            int k;
            register int cbv_13;
            cbv_13=cols_a-5;
#pragma ivdep
#pragma vector always
            for (k=kt; k<=cbv_13; k=k+5) {
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+1]*mat_b[cols_b*(k+1)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+2]*mat_b[cols_b*(k+2)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+3]*mat_b[cols_b*(k+3)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+4]*mat_b[cols_b*(k+4)+j];
            }
            register int cbv_14, cbv_15;
            cbv_14=cols_a-((cols_a-(kt))%5);
            cbv_15=cols_a-1;
#pragma ivdep
#pragma vector always
            for (k=cbv_14; k<=cbv_15; k=k+1) 
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          }
        }
    }
  }
/*@ end @*/
} else if ((rows_a<=6) && (cols_a<=12) && (cols_b<=12)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [2.1068e-05, 2.0808e-05, 2.065e-05, 2.059e-05, 2.0608e-05, 2.0504e-05, 2.0676e-05, 2.0636e-05, 2.068e-05, 2.0842e-05, 2.0758e-05, 2.0636e-05, 2.0794e-05, 2.0794e-05, 2.0842e-05, 2.0798e-05, 2.0774e-05, 2.0696e-05, 2.0778e-05, 2.0866e-05, 2.0818e-05, 2.0652e-05, 2.0396e-05, 2.0516e-05, 2.0584e-05, 2.0634e-05, 2.0632e-05, 2.0494e-05, 2.0532e-05, 2.0516e-05, 2.0474e-05, 2.0588e-05, 2.0594e-05, 2.0652e-05, 2.0474e-05, 2.072e-05, 2.0674e-05, 2.0728e-05, 2.0796e-05, 2.0778e-05, 2.0714e-05, 2.7918e-05, 2.0566e-05, 2.068e-05, 2.0552e-05, 2.0536e-05, 2.0632e-05, 2.0598e-05, 2.0556e-05, 2.0528e-05] 
Tuned for specific problem sizes: 
  cols_a = 12 
  cols_b = 12 
  rows_a = 6 
Best performance parameters: 
  CFLAGS = -O1 
  RT0_I = 1 
  RT0_J = 1 
  RT1_I = 1 
  RT1_J = 1 
  RT1_K = 1 
  U_I = 1 
  U_I0 = 1 
  U_J = 1 
  U_J0 = 1 
  U_K = 1 
  VEC = False 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  for (i=0; i<=rows_a-1; i++ ) {
    for (j=0; j<=cols_b-1; j++ ) {
      mat_c[j+cols_b*i]=0;
    }
  }
  for (i=0; i<=rows_a-1; i++ ) {
    for (j=0; j<=cols_b-1; j++ ) {
      for (k=0; k<=cols_a-1; k++ ) {
        mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
      }
    }
  }
/*@ end @*/
} else if ((rows_a<=12) && (cols_a<=6) && (cols_b<=6)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [1.2492e-05, 1.2204e-05, 1.2376e-05, 1.2148e-05, 1.2294e-05, 1.227e-05, 1.2344e-05, 1.2228e-05, 1.2296e-05, 1.2152e-05, 1.204e-05, 1.2258e-05, 1.2332e-05, 1.2044e-05, 1.1338e-05, 1.2272e-05, 1.2062e-05, 1.229e-05, 1.2206e-05, 1.2176e-05, 1.213e-05, 1.2114e-05, 1.1998e-05, 1.1878e-05, 1.1966e-05, 1.2054e-05, 1.2642e-05, 1.1896e-05, 1.1856e-05, 1.178e-05, 1.1958e-05, 1.2064e-05, 1.2086e-05, 1.1998e-05, 1.2058e-05, 1.2294e-05, 1.1928e-05, 1.2458e-05, 1.211e-05, 1.2084e-05, 1.1956e-05, 1.2258e-05, 1.2294e-05, 1.2142e-05, 1.226e-05, 1.2148e-05, 1.2096e-05, 1.2138e-05, 1.2158e-05, 1.1964e-05] 
Tuned for specific problem sizes: 
  cols_a = 6 
  cols_b = 6 
  rows_a = 12 
Best performance parameters: 
  CFLAGS = -O1 
  RT0_I = 6 
  RT0_J = 1 
  RT1_I = 2 
  RT1_J = 2 
  RT1_K = 1 
  U_I = 1 
  U_I0 = 2 
  U_J = 4 
  U_J0 = 3 
  U_K = 1 
  VEC = False 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  {
    for (it=0; it<=rows_a-6; it=it+6) {
      {
        int j;
        for (j=0; j<=cols_b-3; j=j+3) {
          mat_c[j+cols_b*it]=0;
          mat_c[j+cols_b*(it+1)]=0;
          mat_c[j+cols_b*(it+2)]=0;
          mat_c[j+cols_b*(it+3)]=0;
          mat_c[j+cols_b*(it+4)]=0;
          mat_c[j+cols_b*(it+5)]=0;
          mat_c[j+cols_b*it+1]=0;
          mat_c[j+cols_b*(it+1)+1]=0;
          mat_c[j+cols_b*(it+2)+1]=0;
          mat_c[j+cols_b*(it+3)+1]=0;
          mat_c[j+cols_b*(it+4)+1]=0;
          mat_c[j+cols_b*(it+5)+1]=0;
          mat_c[j+cols_b*it+2]=0;
          mat_c[j+cols_b*(it+1)+2]=0;
          mat_c[j+cols_b*(it+2)+2]=0;
          mat_c[j+cols_b*(it+3)+2]=0;
          mat_c[j+cols_b*(it+4)+2]=0;
          mat_c[j+cols_b*(it+5)+2]=0;
        }
        for (j=cols_b-((cols_b-(0))%3); j<=cols_b-1; j=j+1) {
          mat_c[j+cols_b*it]=0;
          mat_c[j+cols_b*(it+1)]=0;
          mat_c[j+cols_b*(it+2)]=0;
          mat_c[j+cols_b*(it+3)]=0;
          mat_c[j+cols_b*(it+4)]=0;
          mat_c[j+cols_b*(it+5)]=0;
        }
      }
    }
    {
      int i;
      for (i=it; i<=rows_a-2; i=i+2) {
        int j;
        for (j=0; j<=cols_b-3; j=j+3) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*i+1]=0;
          mat_c[j+cols_b*i+2]=0;
          mat_c[j+cols_b*(i+1)]=0;
          mat_c[j+cols_b*(i+1)+1]=0;
          mat_c[j+cols_b*(i+1)+2]=0;
        }
        for (j=cols_b-((cols_b-(0))%3); j<=cols_b-1; j=j+1) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*(i+1)]=0;
        }
      }
      for (i=rows_a-((rows_a-(it))%2); i<=rows_a-1; i=i+1) {
        int j;
        for (j=0; j<=cols_b-3; j=j+3) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*i+1]=0;
          mat_c[j+cols_b*i+2]=0;
        }
        for (j=cols_b-((cols_b-(0))%3); j<=cols_b-1; j=j+1) 
          mat_c[j+cols_b*i]=0;
      }
    }
  }
  {
    for (it=0; it<=rows_a-2; it=it+2) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[jt+cols_b*it]=mat_c[jt+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+jt];
          mat_c[(jt+1)+cols_b*it]=mat_c[(jt+1)+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+(jt+1)];
          mat_c[jt+cols_b*(it+1)]=mat_c[jt+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+jt];
          mat_c[(jt+1)+cols_b*(it+1)]=mat_c[(jt+1)+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+(jt+1)];
        }
      }
      {
        int j;
        for (j=jt; j<=cols_b-4; j=j+4) {
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*it+1]=mat_c[j+cols_b*it+1]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j+1];
            mat_c[j+cols_b*(it+1)+1]=mat_c[j+cols_b*(it+1)+1]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j+1];
            mat_c[j+cols_b*it+2]=mat_c[j+cols_b*it+2]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j+2];
            mat_c[j+cols_b*(it+1)+2]=mat_c[j+cols_b*(it+1)+2]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j+2];
            mat_c[j+cols_b*it+3]=mat_c[j+cols_b*it+3]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j+3];
            mat_c[j+cols_b*(it+1)+3]=mat_c[j+cols_b*(it+1)+3]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j+3];
          }
        }
        for (j=cols_b-((cols_b-(jt))%4); j<=cols_b-1; j=j+1) 
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
          }
      }
    }
    for (i=it; i<=rows_a-1; i=i+1) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[jt+cols_b*i]=mat_c[jt+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+jt];
          mat_c[(jt+1)+cols_b*i]=mat_c[(jt+1)+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+(jt+1)];
        }
      }
      {
        int j;
        for (j=jt; j<=cols_b-4; j=j+4) {
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*i+1]=mat_c[j+cols_b*i+1]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+1];
            mat_c[j+cols_b*i+2]=mat_c[j+cols_b*i+2]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+2];
            mat_c[j+cols_b*i+3]=mat_c[j+cols_b*i+3]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+3];
          }
        }
        for (j=cols_b-((cols_b-(jt))%4); j<=cols_b-1; j=j+1) 
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          }
      }
    }
  }
/*@ end @*/
} else if ((rows_a<=12) && (cols_a<=6) && (cols_b<=12)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [2.2718e-05, 2.2334e-05, 2.2274e-05, 2.205e-05, 2.213e-05, 2.2066e-05, 2.2318e-05, 2.2274e-05, 2.204e-05, 2.2132e-05, 2.2116e-05, 2.2338e-05, 2.2146e-05, 2.2376e-05, 2.2324e-05, 2.2184e-05, 2.2342e-05, 2.2274e-05, 2.2358e-05, 2.2316e-05, 2.2252e-05, 2.2358e-05, 2.2218e-05, 2.2234e-05, 2.227e-05, 2.2056e-05, 2.1994e-05, 2.2052e-05, 2.1918e-05, 2.2036e-05, 2.2124e-05, 2.2214e-05, 2.2022e-05, 2.2186e-05, 2.2102e-05, 2.1964e-05, 2.2148e-05, 2.2118e-05, 2.2052e-05, 2.2202e-05, 2.204e-05, 2.2248e-05, 2.2164e-05, 2.2122e-05, 2.2292e-05, 2.1982e-05, 2.2008e-05, 2.2088e-05, 2.2214e-05, 2.2042e-05] 
Tuned for specific problem sizes: 
  cols_a = 6 
  cols_b = 12 
  rows_a = 12 
Best performance parameters: 
  CFLAGS = -O1 
  RT0_I = 1 
  RT0_J = 1 
  RT1_I = 1 
  RT1_J = 1 
  RT1_K = 1 
  U_I = 1 
  U_I0 = 1 
  U_J = 1 
  U_J0 = 1 
  U_K = 1 
  VEC = False 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  for (i=0; i<=rows_a-1; i++ ) {
    for (j=0; j<=cols_b-1; j++ ) {
      mat_c[j+cols_b*i]=0;
    }
  }
  for (i=0; i<=rows_a-1; i++ ) {
    for (j=0; j<=cols_b-1; j++ ) {
      for (k=0; k<=cols_a-1; k++ ) {
        mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
      }
    }
  }
/*@ end @*/
} else if ((rows_a<=12) && (cols_a<=12) && (cols_b<=6)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [2.2888e-05, 2.303e-05, 2.307e-05, 2.254e-05, 2.2968e-05, 2.2648e-05, 2.2978e-05, 2.2882e-05, 2.279e-05, 2.2814e-05, 2.275e-05, 2.2898e-05, 2.2662e-05, 2.2752e-05, 2.2674e-05, 2.2616e-05, 2.2594e-05, 2.2736e-05, 2.2836e-05, 2.2536e-05, 2.2246e-05, 2.2846e-05, 2.2792e-05, 2.3058e-05, 2.2428e-05, 2.3124e-05, 2.2546e-05, 2.3056e-05, 2.278e-05, 2.2624e-05, 2.2832e-05, 2.2998e-05, 2.2982e-05, 2.3322e-05, 2.271e-05, 2.3222e-05, 2.25e-05, 2.282e-05, 2.2974e-05, 2.2796e-05, 2.3152e-05, 2.2376e-05, 2.2718e-05, 2.2656e-05, 2.2864e-05, 2.2698e-05, 2.307e-05, 2.308e-05, 2.318e-05, 2.2856e-05] 
Tuned for specific problem sizes: 
  cols_a = 12 
  cols_b = 6 
  rows_a = 12 
Best performance parameters: 
  CFLAGS = -O1 
  RT0_I = 6 
  RT0_J = 1 
  RT1_I = 2 
  RT1_J = 2 
  RT1_K = 1 
  U_I = 1 
  U_I0 = 2 
  U_J = 4 
  U_J0 = 3 
  U_K = 1 
  VEC = False 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  {
    for (it=0; it<=rows_a-6; it=it+6) {
      {
        int j;
        for (j=0; j<=cols_b-3; j=j+3) {
          mat_c[j+cols_b*it]=0;
          mat_c[j+cols_b*(it+1)]=0;
          mat_c[j+cols_b*(it+2)]=0;
          mat_c[j+cols_b*(it+3)]=0;
          mat_c[j+cols_b*(it+4)]=0;
          mat_c[j+cols_b*(it+5)]=0;
          mat_c[j+cols_b*it+1]=0;
          mat_c[j+cols_b*(it+1)+1]=0;
          mat_c[j+cols_b*(it+2)+1]=0;
          mat_c[j+cols_b*(it+3)+1]=0;
          mat_c[j+cols_b*(it+4)+1]=0;
          mat_c[j+cols_b*(it+5)+1]=0;
          mat_c[j+cols_b*it+2]=0;
          mat_c[j+cols_b*(it+1)+2]=0;
          mat_c[j+cols_b*(it+2)+2]=0;
          mat_c[j+cols_b*(it+3)+2]=0;
          mat_c[j+cols_b*(it+4)+2]=0;
          mat_c[j+cols_b*(it+5)+2]=0;
        }
        for (j=cols_b-((cols_b-(0))%3); j<=cols_b-1; j=j+1) {
          mat_c[j+cols_b*it]=0;
          mat_c[j+cols_b*(it+1)]=0;
          mat_c[j+cols_b*(it+2)]=0;
          mat_c[j+cols_b*(it+3)]=0;
          mat_c[j+cols_b*(it+4)]=0;
          mat_c[j+cols_b*(it+5)]=0;
        }
      }
    }
    {
      int i;
      for (i=it; i<=rows_a-2; i=i+2) {
        int j;
        for (j=0; j<=cols_b-3; j=j+3) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*i+1]=0;
          mat_c[j+cols_b*i+2]=0;
          mat_c[j+cols_b*(i+1)]=0;
          mat_c[j+cols_b*(i+1)+1]=0;
          mat_c[j+cols_b*(i+1)+2]=0;
        }
        for (j=cols_b-((cols_b-(0))%3); j<=cols_b-1; j=j+1) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*(i+1)]=0;
        }
      }
      for (i=rows_a-((rows_a-(it))%2); i<=rows_a-1; i=i+1) {
        int j;
        for (j=0; j<=cols_b-3; j=j+3) {
          mat_c[j+cols_b*i]=0;
          mat_c[j+cols_b*i+1]=0;
          mat_c[j+cols_b*i+2]=0;
        }
        for (j=cols_b-((cols_b-(0))%3); j<=cols_b-1; j=j+1) 
          mat_c[j+cols_b*i]=0;
      }
    }
  }
  {
    for (it=0; it<=rows_a-2; it=it+2) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[jt+cols_b*it]=mat_c[jt+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+jt];
          mat_c[(jt+1)+cols_b*it]=mat_c[(jt+1)+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+(jt+1)];
          mat_c[jt+cols_b*(it+1)]=mat_c[jt+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+jt];
          mat_c[(jt+1)+cols_b*(it+1)]=mat_c[(jt+1)+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+(jt+1)];
        }
      }
      {
        int j;
        for (j=jt; j<=cols_b-4; j=j+4) {
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*it+1]=mat_c[j+cols_b*it+1]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j+1];
            mat_c[j+cols_b*(it+1)+1]=mat_c[j+cols_b*(it+1)+1]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j+1];
            mat_c[j+cols_b*it+2]=mat_c[j+cols_b*it+2]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j+2];
            mat_c[j+cols_b*(it+1)+2]=mat_c[j+cols_b*(it+1)+2]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j+2];
            mat_c[j+cols_b*it+3]=mat_c[j+cols_b*it+3]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j+3];
            mat_c[j+cols_b*(it+1)+3]=mat_c[j+cols_b*(it+1)+3]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j+3];
          }
        }
        for (j=cols_b-((cols_b-(jt))%4); j<=cols_b-1; j=j+1) 
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
          }
      }
    }
    for (i=it; i<=rows_a-1; i=i+1) {
      for (jt=0; jt<=cols_b-2; jt=jt+2) {
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[jt+cols_b*i]=mat_c[jt+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+jt];
          mat_c[(jt+1)+cols_b*i]=mat_c[(jt+1)+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+(jt+1)];
        }
      }
      {
        int j;
        for (j=jt; j<=cols_b-4; j=j+4) {
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*i+1]=mat_c[j+cols_b*i+1]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+1];
            mat_c[j+cols_b*i+2]=mat_c[j+cols_b*i+2]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+2];
            mat_c[j+cols_b*i+3]=mat_c[j+cols_b*i+3]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+3];
          }
        }
        for (j=cols_b-((cols_b-(jt))%4); j<=cols_b-1; j=j+1) 
          for (k=0; k<=cols_a-1; k++ ) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          }
      }
    }
  }
/*@ end @*/
} else if ((rows_a<=12) && (cols_a<=12) && (cols_b<=12)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [4.6124e-05, 4.5062e-05, 4.5122e-05, 4.5212e-05, 4.471e-05, 4.507e-05, 4.5922e-05, 4.505e-05, 4.4674e-05, 4.4092e-05, 4.4988e-05, 4.5204e-05, 4.5574e-05, 4.5496e-05, 4.5094e-05, 4.509e-05, 4.451e-05, 6.385e-05, 4.5018e-05, 4.4984e-05, 4.4974e-05, 4.5678e-05, 4.5034e-05, 4.495e-05, 4.4852e-05, 4.5122e-05, 4.503e-05, 4.4912e-05, 4.4086e-05, 4.5644e-05, 4.5298e-05, 4.4564e-05, 4.5604e-05, 4.4902e-05, 4.5856e-05, 4.479e-05, 4.591e-05, 4.5474e-05, 4.5288e-05, 4.502e-05, 4.5592e-05, 4.5034e-05, 4.5406e-05, 4.5458e-05, 4.445e-05, 4.5466e-05, 4.6026e-05, 4.4816e-05, 4.4832e-05, 4.4358e-05] 
Tuned for specific problem sizes: 
  cols_a = 12 
  cols_b = 12 
  rows_a = 12 
Best performance parameters: 
  CFLAGS = -O3 
  RT0_I = 1 
  RT0_J = 2 
  RT1_I = 2 
  RT1_J = 1 
  RT1_K = 2 
  U_I = 3 
  U_I0 = 3 
  U_J = 1 
  U_J0 = 1 
  U_K = 3 
  VEC = True 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j'],[RT0_I,RT0_J])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always']),
      regtile = (['i','j','k'],[RT1_I,RT1_J,RT1_K])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  {
    int i;
    for (i=0; i<=rows_a-3; i=i+3) {
      register int cbv_1;
      cbv_1=cols_b-2;
#pragma ivdep
#pragma vector always
      for (jt=0; jt<=cbv_1; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[jt+cols_b*i+1]=0;
        mat_c[jt+cols_b*(i+1)]=0;
        mat_c[jt+cols_b*(i+1)+1]=0;
        mat_c[jt+cols_b*(i+2)]=0;
        mat_c[jt+cols_b*(i+2)+1]=0;
      }
      register int cbv_2;
      cbv_2=cols_b-1;
#pragma ivdep
#pragma vector always
      for (j=jt; j<=cbv_2; j=j+1) {
        mat_c[j+cols_b*i]=0;
        mat_c[j+cols_b*(i+1)]=0;
        mat_c[j+cols_b*(i+2)]=0;
      }
    }
    for (i=rows_a-((rows_a-(0))%3); i<=rows_a-1; i=i+1) {
      register int cbv_3;
      cbv_3=cols_b-2;
#pragma ivdep
#pragma vector always
      for (jt=0; jt<=cbv_3; jt=jt+2) {
        mat_c[jt+cols_b*i]=0;
        mat_c[(jt+1)+cols_b*i]=0;
      }
      register int cbv_4;
      cbv_4=cols_b-1;
#pragma ivdep
#pragma vector always
      for (j=jt; j<=cbv_4; j=j+1) {
        mat_c[j+cols_b*i]=0;
      }
    }
  }
  {
    for (it=0; it<=rows_a-2; it=it+2) {
      for (j=0; j<=cols_b-1; j++ ) {
        register int cbv_1;
        cbv_1=cols_a-2;
#pragma ivdep
#pragma vector always
        for (kt=0; kt<=cbv_1; kt=kt+2) {
          mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+kt]*mat_b[cols_b*kt+j];
          mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+(kt+1)]*mat_b[cols_b*(kt+1)+j];
          mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+kt]*mat_b[cols_b*kt+j];
          mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+(kt+1)]*mat_b[cols_b*(kt+1)+j];
        }
        {
          int k;
          register int cbv_2;
          cbv_2=cols_a-3;
#pragma ivdep
#pragma vector always
          for (k=kt; k<=cbv_2; k=k+3) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k+1]*mat_b[cols_b*(k+1)+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k+1]*mat_b[cols_b*(k+1)+j];
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k+2]*mat_b[cols_b*(k+2)+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k+2]*mat_b[cols_b*(k+2)+j];
          }
          register int cbv_3, cbv_4;
          cbv_3=cols_a-((cols_a-(kt))%3);
          cbv_4=cols_a-1;
#pragma ivdep
#pragma vector always
          for (k=cbv_3; k<=cbv_4; k=k+1) {
            mat_c[j+cols_b*it]=mat_c[j+cols_b*it]+mat_a[cols_a*it+k]*mat_b[cols_b*k+j];
            mat_c[j+cols_b*(it+1)]=mat_c[j+cols_b*(it+1)]+mat_a[cols_a*(it+1)+k]*mat_b[cols_b*k+j];
          }
        }
      }
    }
    {
      int i;
      for (i=it; i<=rows_a-3; i=i+3) {
        for (j=0; j<=cols_b-1; j++ ) {
          register int cbv_5;
          cbv_5=cols_a-2;
#pragma ivdep
#pragma vector always
          for (kt=0; kt<=cbv_5; kt=kt+2) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+kt]*mat_b[cols_b*kt+j];
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+kt+1]*mat_b[cols_b*(kt+1)+j];
            mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+kt]*mat_b[cols_b*kt+j];
            mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+kt+1]*mat_b[cols_b*(kt+1)+j];
            mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+kt]*mat_b[cols_b*kt+j];
            mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+kt+1]*mat_b[cols_b*(kt+1)+j];
          }
          {
            int k;
            register int cbv_6;
            cbv_6=cols_a-3;
#pragma ivdep
#pragma vector always
            for (k=kt; k<=cbv_6; k=k+3) {
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+1]*mat_b[cols_b*(k+1)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+2]*mat_b[cols_b*(k+2)+j];
            }
            register int cbv_7, cbv_8;
            cbv_7=cols_a-((cols_a-(kt))%3);
            cbv_8=cols_a-1;
#pragma ivdep
#pragma vector always
            for (k=cbv_7; k<=cbv_8; k=k+1) 
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          }
          {
            int k;
            register int cbv_9;
            cbv_9=cols_a-3;
#pragma ivdep
#pragma vector always
            for (k=kt; k<=cbv_9; k=k+3) {
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j];
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k+1]*mat_b[cols_b*(k+1)+j];
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k+2]*mat_b[cols_b*(k+2)+j];
            }
            register int cbv_10, cbv_11;
            cbv_10=cols_a-((cols_a-(kt))%3);
            cbv_11=cols_a-1;
#pragma ivdep
#pragma vector always
            for (k=cbv_10; k<=cbv_11; k=k+1) 
              mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j];
          }
          {
            int k;
            register int cbv_12;
            cbv_12=cols_a-3;
#pragma ivdep
#pragma vector always
            for (k=kt; k<=cbv_12; k=k+3) {
              mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j];
              mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+k+1]*mat_b[cols_b*(k+1)+j];
              mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+k+2]*mat_b[cols_b*(k+2)+j];
            }
            register int cbv_13, cbv_14;
            cbv_13=cols_a-((cols_a-(kt))%3);
            cbv_14=cols_a-1;
#pragma ivdep
#pragma vector always
            for (k=cbv_13; k<=cbv_14; k=k+1) 
              mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j];
          }
        }
      }
      for (i=rows_a-((rows_a-(it))%3); i<=rows_a-1; i=i+1) 
        for (j=0; j<=cols_b-1; j++ ) {
          register int cbv_15;
          cbv_15=cols_a-2;
#pragma ivdep
#pragma vector always
          for (kt=0; kt<=cbv_15; kt=kt+2) {
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+kt]*mat_b[cols_b*kt+j];
            mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+(kt+1)]*mat_b[cols_b*(kt+1)+j];
          }
          {
            int k;
            register int cbv_16;
            cbv_16=cols_a-3;
#pragma ivdep
#pragma vector always
            for (k=kt; k<=cbv_16; k=k+3) {
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+1]*mat_b[cols_b*(k+1)+j];
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k+2]*mat_b[cols_b*(k+2)+j];
            }
            register int cbv_17, cbv_18;
            cbv_17=cols_a-((cols_a-(kt))%3);
            cbv_18=cols_a-1;
#pragma ivdep
#pragma vector always
            for (k=cbv_17; k<=cbv_18; k=k+1) 
              mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          }
        }
    }
  }
/*@ end @*/
}
/*@ end @*/
}
