#include "../../linear_algebra.h"

void add_matrix(KALMAN_TYPE* mat_a, int rows, int cols, KALMAN_TYPE* mat_b, KALMAN_TYPE* mat_c)  {

/*@ begin PerfTuning (

 def build {
   arg build_command = 'icc';
   #arg libs = '-lrt';  # Only needed on linux
 } 

 def performance_counter {
   arg repetitions = 100;
 }

 def performance_params {  
  param U_I[] = range(1,7);
  param U_J[] = range(1,7);

  param VEC[] = [False,True];
 }
 
 def input_params {
  let N = [6];
  param rows[] = N;
  param cols[] = N;
 }
 
 def input_vars {
   decl dynamic double mat_a[rows*cols] = random;
   decl dynamic double mat_b[rows*cols] = random;
   decl dynamic double mat_c[rows*cols] = 0;
 }
 
 def search {
   arg algorithm = 'Exhaustive';
 }

) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [1.224e-06, 5.4e-07, 5.14e-07, 5.36e-07, 5.07e-07, 5.11e-07, 5.12e-07, 5.13e-07, 5.08e-07, 5.09e-07, 5.02e-07, 5.12e-07, 5.08e-07, 5.15e-07, 5.06e-07, 5.17e-07, 5.14e-07, 5.14e-07, 5.07e-07, 5.15e-07, 5.11e-07, 5.11e-07, 5.11e-07, 5.18e-07, 5.11e-07, 5.07e-07, 5.17e-07, 5.1e-07, 5.1e-07, 5.12e-07, 5.12e-07, 5.09e-07, 5.07e-07, 4.98e-07, 5.09e-07, 5.09e-07, 5.05e-07, 5.11e-07, 5.11e-07, 5.1e-07, 5.12e-07, 5.14e-07, 5.19e-07, 5.05e-07, 5.05e-07, 5.04e-07, 5.04e-07, 5e-07, 5.1e-07, 5.06e-07, 5.09e-07, 5.09e-07, 5.15e-07, 5.12e-07, 5.17e-07, 5.1e-07, 5.04e-07, 5.06e-07, 5.03e-07, 5.13e-07, 5.13e-07, 5.04e-07, 5.14e-07, 5.08e-07, 5.07e-07, 5.07e-07, 5.06e-07, 5.1e-07, 5.08e-07, 5.13e-07, 5.11e-07, 5.06e-07, 5.08e-07, 5.09e-07, 5.09e-07, 5.05e-07, 5.08e-07, 5.15e-07, 5.11e-07, 5.09e-07, 5.09e-07, 5.12e-07, 5.12e-07, 5.13e-07, 5.04e-07, 5.09e-07, 5.08e-07, 5.13e-07, 5.27e-07, 5.13e-07, 5.07e-07, 5.1e-07, 5.14e-07, 5.11e-07, 5.09e-07, 5.15e-07, 5.11e-07, 5.09e-07, 5.13e-07, 5.05e-07] 
Tuned for specific problem sizes: 
  cols = 6 
  rows = 6 
Best performance parameters: 
  U_I = 5 
  U_J = 3 
  VEC = False 
--**/


int i, j;
int it, jt;

/*@ begin Loop (  
  transform Composite(
    unrolljam = (['i','j'],[U_I,U_J]),
    vector = (VEC, ['ivdep','vector always'])
)
  for (i = 0; i <= rows-1; i++) {
    for (j = 0; j <= cols-1; j++) {
      mat_c[ cols * i + j] = mat_a[ cols * i + j] + mat_b[ cols * i + j];
    }
  }
) @*/
{
  int i;
  for (i=0; i<=rows-5; i=i+5) {
    int j;
    for (j=0; j<=cols-3; j=j+3) {
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
      mat_c[cols*i+j+1]=mat_a[cols*i+j+1]+mat_b[cols*i+j+1];
      mat_c[cols*i+j+2]=mat_a[cols*i+j+2]+mat_b[cols*i+j+2];
      mat_c[cols*(i+1)+j]=mat_a[cols*(i+1)+j]+mat_b[cols*(i+1)+j];
      mat_c[cols*(i+1)+j+1]=mat_a[cols*(i+1)+j+1]+mat_b[cols*(i+1)+j+1];
      mat_c[cols*(i+1)+j+2]=mat_a[cols*(i+1)+j+2]+mat_b[cols*(i+1)+j+2];
      mat_c[cols*(i+2)+j]=mat_a[cols*(i+2)+j]+mat_b[cols*(i+2)+j];
      mat_c[cols*(i+2)+j+1]=mat_a[cols*(i+2)+j+1]+mat_b[cols*(i+2)+j+1];
      mat_c[cols*(i+2)+j+2]=mat_a[cols*(i+2)+j+2]+mat_b[cols*(i+2)+j+2];
      mat_c[cols*(i+3)+j]=mat_a[cols*(i+3)+j]+mat_b[cols*(i+3)+j];
      mat_c[cols*(i+3)+j+1]=mat_a[cols*(i+3)+j+1]+mat_b[cols*(i+3)+j+1];
      mat_c[cols*(i+3)+j+2]=mat_a[cols*(i+3)+j+2]+mat_b[cols*(i+3)+j+2];
      mat_c[cols*(i+4)+j]=mat_a[cols*(i+4)+j]+mat_b[cols*(i+4)+j];
      mat_c[cols*(i+4)+j+1]=mat_a[cols*(i+4)+j+1]+mat_b[cols*(i+4)+j+1];
      mat_c[cols*(i+4)+j+2]=mat_a[cols*(i+4)+j+2]+mat_b[cols*(i+4)+j+2];
    }
    for (j=cols-((cols-(0))%3); j<=cols-1; j=j+1) {
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
      mat_c[cols*(i+1)+j]=mat_a[cols*(i+1)+j]+mat_b[cols*(i+1)+j];
      mat_c[cols*(i+2)+j]=mat_a[cols*(i+2)+j]+mat_b[cols*(i+2)+j];
      mat_c[cols*(i+3)+j]=mat_a[cols*(i+3)+j]+mat_b[cols*(i+3)+j];
      mat_c[cols*(i+4)+j]=mat_a[cols*(i+4)+j]+mat_b[cols*(i+4)+j];
    }
  }
  for (i=rows-((rows-(0))%5); i<=rows-1; i=i+1) {
    int j;
    for (j=0; j<=cols-3; j=j+3) {
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
      mat_c[cols*i+j+1]=mat_a[cols*i+j+1]+mat_b[cols*i+j+1];
      mat_c[cols*i+j+2]=mat_a[cols*i+j+2]+mat_b[cols*i+j+2];
    }
    for (j=cols-((cols-(0))%3); j<=cols-1; j=j+1) 
      mat_c[cols*i+j]=mat_a[cols*i+j]+mat_b[cols*i+j];
  }
}
/*@ end @*/
/*@ end @*/

}