void add_matrix(TYPE* mat_a, int rows, int cols, TYPE* mat_b, TYPE* mat_c) {


  /*@ begin PerfTuning (
   def build {
     arg build_command = 'gcc';
     #arg libs = '-lrt';  # Only needed on linux
   } 
   def performance_counter {
     arg repetitions = 5;
   }
   def performance_params {  
     param UF[] = range(1,11);
     param CFLAGS[] = ['-O0', '-O1', '-O2', '-O3'];
     #constraint divisible_by_two = (UF % 2 == 0);
   }
   def input_params {
    let R = [100];
    let C = [100];
    param rows[] = R;
    param cols[] = C;
   }
   def input_vars {
     decl dynamic double mat_a[rows*cols] = random;
     decl dynamic double mat_b[rows*cols] = random;
     decl dynamic double mat_c[rows*cols] = 0;
   }
   def search {
     arg algorithm = 'Exhaustive';
   }
  ) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [0.000156296, 0.000155991, 0.000155124, 0.000155161, 0.000155217] 
Tuned for specific problem sizes: 
  cols = 100 
  rows = 100 
Best performance parameters: 
  CFLAGS = -O3 
  UF = 6 
--**/


  int i, j;
  int ind, row;


  /*@ begin Loop ( 
    transform Unroll(ufactor=UF) 
    for (i = 0; i <= rows-1; i++) {
      row = cols * i;
      for (j = 0; j <= cols-1; j++) {
        ind = row + j;
        mat_c[ind] = mat_a[ind] + mat_b[ind];
      }
    }
  ) @*/
  {
    int i;
    for (i=0; i<=rows-6; i=i+6) {
      row=cols*i;
      for (j=0; j<=cols-1; j++ ) {
        ind=row+j;
        mat_c[ind]=mat_a[ind]+mat_b[ind];
      }
      row=cols*(i+1);
      for (j=0; j<=cols-1; j++ ) {
        ind=row+j;
        mat_c[ind]=mat_a[ind]+mat_b[ind];
      }
      row=cols*(i+2);
      for (j=0; j<=cols-1; j++ ) {
        ind=row+j;
        mat_c[ind]=mat_a[ind]+mat_b[ind];
      }
      row=cols*(i+3);
      for (j=0; j<=cols-1; j++ ) {
        ind=row+j;
        mat_c[ind]=mat_a[ind]+mat_b[ind];
      }
      row=cols*(i+4);
      for (j=0; j<=cols-1; j++ ) {
        ind=row+j;
        mat_c[ind]=mat_a[ind]+mat_b[ind];
      }
      row=cols*(i+5);
      for (j=0; j<=cols-1; j++ ) {
        ind=row+j;
        mat_c[ind]=mat_a[ind]+mat_b[ind];
      }
    }
    for (i=rows-((rows-(0))%6); i<=rows-1; i=i+1) {
      row=cols*i;
      for (j=0; j<=cols-1; j++ ) {
        ind=row+j;
        mat_c[ind]=mat_a[ind]+mat_b[ind];
      }
    }
  }
  /*@ end @*/
    /*@ end @*/

}