test_linear:
		gcc test_linear_algebra.c linear_algebra.c -o test_linear.out

test_kalman:
		gcc test-kalman.c kalman_filter.c linear_algebra.c -o test_kalman.out

test_kalman_db:
		gcc test-kalman.c kalman_filter.c linear_algebra.c -g -o test_kalman.out