#include "../../linear_algebra.h"


void transpose_matrix(TYPE* mat_a, int rows_a, int cols_a, TYPE* mat_c) {
 

/*@ begin PerfTuning (

 def build {
   arg build_command = 'gcc';
   #arg libs = '-lrt';  # Only needed on linux
 } 

 def performance_counter {
   arg repetitions = 5;
 }

 def performance_params {  
  param U_I[] = range(1,31);
  param U_J[] = range(1,31);

  param VEC[] = [False,True];

  param CFLAGS[] = ['-O0', '-O1', '-O2', '-O3'];
  constraint unroll_limit = ((U_I == 1) or (U_J == 1));

 }
 
 def input_params {
  let R = [100];
  let C = [100];
  param rows_a[] = R;
  param cols_a[] = C;
 }
 
 def input_vars {
   decl dynamic double mat_a[rows_a*cols_a] = random;
   decl dynamic double mat_c[rows_a*cols_a] = 0;
 }
 
 def search {
   arg algorithm = 'Exhaustive';
 }

) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [7.5444e-05, 7.364e-05, 7.3177e-05, 7.3142e-05, 7.3139e-05] 
Tuned for specific problem sizes: 
  cols_a = 100 
  rows_a = 100 
Best performance parameters: 
  CFLAGS = -O0 
  U_I = 25 
  U_J = 1 
  VEC = True 
--**/


  int i, j;
  int a_row;

/*@ begin Loop (  
  transform Composite(
    unrolljam = (['i','j'],[U_I,U_J]),
    vector = (VEC, ['ivdep','vector always'])
  )
  for (i = 0; i <= rows_a-1; i++) {
    a_row = cols_a * i;
    for (j = 0; j <= cols_a-1; j++) {
      mat_c[rows_a * j + i] = mat_a[a_row + j];
    }
  }
) @*/
{
  int i;
  for (i=0; i<=rows_a-25; i=i+25) {
    a_row=cols_a*i;
    a_row=cols_a*(i+1);
    a_row=cols_a*(i+2);
    a_row=cols_a*(i+3);
    a_row=cols_a*(i+4);
    a_row=cols_a*(i+5);
    a_row=cols_a*(i+6);
    a_row=cols_a*(i+7);
    a_row=cols_a*(i+8);
    a_row=cols_a*(i+9);
    a_row=cols_a*(i+10);
    a_row=cols_a*(i+11);
    a_row=cols_a*(i+12);
    a_row=cols_a*(i+13);
    a_row=cols_a*(i+14);
    a_row=cols_a*(i+15);
    a_row=cols_a*(i+16);
    a_row=cols_a*(i+17);
    a_row=cols_a*(i+18);
    a_row=cols_a*(i+19);
    a_row=cols_a*(i+20);
    a_row=cols_a*(i+21);
    a_row=cols_a*(i+22);
    a_row=cols_a*(i+23);
    a_row=cols_a*(i+24);
    register int cbv_1;
    cbv_1=cols_a-1;
#pragma ivdep
#pragma vector always
    for (j=0; j<=cbv_1; j++ ) {
      mat_c[rows_a*j+i]=mat_a[a_row+j];
      mat_c[rows_a*j+i+1]=mat_a[a_row+j];
      mat_c[rows_a*j+i+2]=mat_a[a_row+j];
      mat_c[rows_a*j+i+3]=mat_a[a_row+j];
      mat_c[rows_a*j+i+4]=mat_a[a_row+j];
      mat_c[rows_a*j+i+5]=mat_a[a_row+j];
      mat_c[rows_a*j+i+6]=mat_a[a_row+j];
      mat_c[rows_a*j+i+7]=mat_a[a_row+j];
      mat_c[rows_a*j+i+8]=mat_a[a_row+j];
      mat_c[rows_a*j+i+9]=mat_a[a_row+j];
      mat_c[rows_a*j+i+10]=mat_a[a_row+j];
      mat_c[rows_a*j+i+11]=mat_a[a_row+j];
      mat_c[rows_a*j+i+12]=mat_a[a_row+j];
      mat_c[rows_a*j+i+13]=mat_a[a_row+j];
      mat_c[rows_a*j+i+14]=mat_a[a_row+j];
      mat_c[rows_a*j+i+15]=mat_a[a_row+j];
      mat_c[rows_a*j+i+16]=mat_a[a_row+j];
      mat_c[rows_a*j+i+17]=mat_a[a_row+j];
      mat_c[rows_a*j+i+18]=mat_a[a_row+j];
      mat_c[rows_a*j+i+19]=mat_a[a_row+j];
      mat_c[rows_a*j+i+20]=mat_a[a_row+j];
      mat_c[rows_a*j+i+21]=mat_a[a_row+j];
      mat_c[rows_a*j+i+22]=mat_a[a_row+j];
      mat_c[rows_a*j+i+23]=mat_a[a_row+j];
      mat_c[rows_a*j+i+24]=mat_a[a_row+j];
    }
  }
  for (i=rows_a-((rows_a-(0))%25); i<=rows_a-1; i=i+1) {
    a_row=cols_a*i;
    register int cbv_2;
    cbv_2=cols_a-1;
#pragma ivdep
#pragma vector always
    for (j=0; j<=cbv_2; j++ ) {
      mat_c[rows_a*j+i]=mat_a[a_row+j];
    }
  }
}
/*@ end @*/
/*@ end @*/

}
