#include "../../linear_algebra.h"


void multiply_matrix_by_scalar(KALMAN_TYPE* mat_a, int rows, int cols, KALMAN_TYPE scalar, KALMAN_TYPE* mat_c) {

  /*@ begin PerfTuning (

    def build {
      arg build_command = 'icc';
      #arg libs = '-lrt';  # Only needed on linux
    } 

    def performance_counter {
      arg repetitions = 70;
    }

    def performance_params {  
      param U_I[] = range(1,7);
      param U_J[] = range(1,7);

      param VEC[] = [False,True];
    }

    def input_params {
      let N = [6];
      param rows[] = N;
      param cols[] = N;
    }

    def input_vars {
      decl dynamic double mat_a[rows*cols] = random;
      decl dynamic double mat_b[rows*cols] = random;
      decl dynamic double mat_c[rows*cols] = 0;
      decl double scalar = random;
    }

    def search {
      arg algorithm = 'Exhaustive';
    }

  ) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [1.234e-06, 5.46e-07, 5.1e-07, 5.29e-07, 5.1e-07, 5.13e-07, 5.08e-07, 5.28e-07, 5.09e-07, 5.14e-07, 5.1e-07, 5.06e-07, 5.04e-07, 5.11e-07, 5.09e-07, 5.14e-07, 5.11e-07, 5.15e-07, 5.12e-07, 5.07e-07, 5.09e-07, 5.02e-07, 5.08e-07, 5.07e-07, 5.06e-07, 5.04e-07, 5.12e-07, 5.05e-07, 5.05e-07, 5.17e-07, 5.05e-07, 5.18e-07, 5.01e-07, 5.09e-07, 5.07e-07, 5.12e-07, 5.06e-07, 5.11e-07, 5.02e-07, 5.1e-07, 5.1e-07, 5.08e-07, 5.13e-07, 5.14e-07, 5.11e-07, 5.11e-07, 5.08e-07, 5.08e-07, 5.12e-07, 5.03e-07, 5.13e-07, 5.13e-07, 5.04e-07, 5.07e-07, 5.11e-07, 5.08e-07, 5.02e-07, 5.07e-07, 5.09e-07, 5.05e-07, 5.07e-07, 5.07e-07, 5.05e-07, 5.06e-07, 5.08e-07, 5.07e-07, 5.07e-07, 5.13e-07, 5.13e-07, 5.1e-07] 
Tuned for specific problem sizes: 
  cols = 6 
  rows = 6 
Best performance parameters: 
  U_I = 4 
  U_J = 5 
  VEC = False 
--**/


    
  int i, j, it, jt;
  int ind, row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I,U_J]), 
      vector = (VEC, ['ivdep','vector always'])
    )
    for (i = 0; i <= rows-1; i++) {
      for (j = 0; j <= cols-1; j++) {
        mat_c[cols * i + j] = mat_a[cols * i + j] * scalar;
      }
    }
  ) @*/
  {
    int i;
    for (i=0; i<=rows-4; i=i+4) {
      int j;
      for (j=0; j<=cols-5; j=j+5) {
        mat_c[cols*i+j]=mat_a[cols*i+j]*scalar;
        mat_c[cols*i+j+1]=mat_a[cols*i+j+1]*scalar;
        mat_c[cols*i+j+2]=mat_a[cols*i+j+2]*scalar;
        mat_c[cols*i+j+3]=mat_a[cols*i+j+3]*scalar;
        mat_c[cols*i+j+4]=mat_a[cols*i+j+4]*scalar;
        mat_c[cols*(i+1)+j]=mat_a[cols*(i+1)+j]*scalar;
        mat_c[cols*(i+1)+j+1]=mat_a[cols*(i+1)+j+1]*scalar;
        mat_c[cols*(i+1)+j+2]=mat_a[cols*(i+1)+j+2]*scalar;
        mat_c[cols*(i+1)+j+3]=mat_a[cols*(i+1)+j+3]*scalar;
        mat_c[cols*(i+1)+j+4]=mat_a[cols*(i+1)+j+4]*scalar;
        mat_c[cols*(i+2)+j]=mat_a[cols*(i+2)+j]*scalar;
        mat_c[cols*(i+2)+j+1]=mat_a[cols*(i+2)+j+1]*scalar;
        mat_c[cols*(i+2)+j+2]=mat_a[cols*(i+2)+j+2]*scalar;
        mat_c[cols*(i+2)+j+3]=mat_a[cols*(i+2)+j+3]*scalar;
        mat_c[cols*(i+2)+j+4]=mat_a[cols*(i+2)+j+4]*scalar;
        mat_c[cols*(i+3)+j]=mat_a[cols*(i+3)+j]*scalar;
        mat_c[cols*(i+3)+j+1]=mat_a[cols*(i+3)+j+1]*scalar;
        mat_c[cols*(i+3)+j+2]=mat_a[cols*(i+3)+j+2]*scalar;
        mat_c[cols*(i+3)+j+3]=mat_a[cols*(i+3)+j+3]*scalar;
        mat_c[cols*(i+3)+j+4]=mat_a[cols*(i+3)+j+4]*scalar;
      }
      for (j=cols-((cols-(0))%5); j<=cols-1; j=j+1) {
        mat_c[cols*i+j]=mat_a[cols*i+j]*scalar;
        mat_c[cols*(i+1)+j]=mat_a[cols*(i+1)+j]*scalar;
        mat_c[cols*(i+2)+j]=mat_a[cols*(i+2)+j]*scalar;
        mat_c[cols*(i+3)+j]=mat_a[cols*(i+3)+j]*scalar;
      }
    }
    for (i=rows-((rows-(0))%4); i<=rows-1; i=i+1) {
      int j;
      for (j=0; j<=cols-5; j=j+5) {
        mat_c[cols*i+j]=mat_a[cols*i+j]*scalar;
        mat_c[cols*i+j+1]=mat_a[cols*i+j+1]*scalar;
        mat_c[cols*i+j+2]=mat_a[cols*i+j+2]*scalar;
        mat_c[cols*i+j+3]=mat_a[cols*i+j+3]*scalar;
        mat_c[cols*i+j+4]=mat_a[cols*i+j+4]*scalar;
      }
      for (j=cols-((cols-(0))%5); j<=cols-1; j=j+1) 
        mat_c[cols*i+j]=mat_a[cols*i+j]*scalar;
    }
  }
/*@ end @*/
/*@ end @*/

  
}
