#include "../../linear_algebra.h"

void multiply_matrix(KALMAN_TYPE* mat_a, int rows_a, int cols_a, 
                     KALMAN_TYPE* mat_b, int cols_b, 
                     KALMAN_TYPE* mat_c) {


  /*@ begin PerfTuning (

    def build {
      arg build_command = 'icc';
      #arg libs = '-lrt';  # Only needed on linux
    } 

    def performance_counter {
      arg repetitions = 10;
    }

    def performance_params {  
      param U_I0[] = range(1,7);
      param U_J0[] = range(1,7);
      param U_I[] = range(1,7);
      param U_J[] = range(1,7);
      param U_K[] = range(1,7);

      param VEC[] = [False,True];

    }

    def input_params {
      let N = [6];
      param rows_a[] = N;
      param cols_a[] = N;
      param cols_b[] = N;
    }

    def input_vars {
      decl dynamic double mat_a[rows_a*cols_a] = random;
      decl dynamic double mat_b[cols_b*cols_b] = random;
      decl dynamic double mat_c[rows_a*cols_b] = 0;
    }

    def search {
      arg algorithm = 'Exhaustive';
    }

  ) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [1.411e-06, 4.95e-07, 4.44e-07, 4.46e-07, 4.3e-07, 4.29e-07, 4.28e-07, 4.24e-07, 4.28e-07, 4.3e-07] 
Tuned for specific problem sizes: 
  cols_a = 6 
  cols_b = 6 
  rows_a = 6 
Best performance parameters: 
  U_I = 3 
  U_I0 = 1 
  U_J = 6 
  U_J0 = 4 
  U_K = 1 
  VEC = False 
--**/


  int i, j, k;  
  int it,jt, kt;
  int c_ind, a_row, c_row;


  /*@ begin Loop (  
    transform Composite(
      unrolljam = (['i','j'],[U_I0,U_J0]),
      vector = (VEC, ['ivdep','vector always'])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        mat_c[j + cols_b * i] = 0;
      }
    } 

    transform Composite(
      unrolljam = (['i','j','k'],[U_I,U_J,U_K]),
      vector = (VEC, ['ivdep','vector always'])
    )
    for (i = 0; i <= rows_a-1; i++) {
      for (j = 0; j <= cols_b-1; j++) {
        for (k = 0; k <= cols_a-1; k++) {
          mat_c[j + cols_b * i] += mat_a[cols_a * i + k] * mat_b[cols_b * k + j];
        }
      } 
    }
  ) @*/
  for (i=0; i<=rows_a-1; i++ ) {
    {
      int j;
      for (j=0; j<=cols_b-4; j=j+4) {
        mat_c[j+cols_b*i]=0;
        mat_c[j+cols_b*i+1]=0;
        mat_c[j+cols_b*i+2]=0;
        mat_c[j+cols_b*i+3]=0;
      }
      for (j=cols_b-((cols_b-(0))%4); j<=cols_b-1; j=j+1) 
        mat_c[j+cols_b*i]=0;
    }
  }
  {
    int i;
    for (i=0; i<=rows_a-3; i=i+3) {
      int j;
      for (j=0; j<=cols_b-6; j=j+6) {
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*i+1]=mat_c[j+cols_b*i+1]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+1];
          mat_c[j+cols_b*i+2]=mat_c[j+cols_b*i+2]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+2];
          mat_c[j+cols_b*i+3]=mat_c[j+cols_b*i+3]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+3];
          mat_c[j+cols_b*i+4]=mat_c[j+cols_b*i+4]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+4];
          mat_c[j+cols_b*i+5]=mat_c[j+cols_b*i+5]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+5];
          mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*(i+1)+1]=mat_c[j+cols_b*(i+1)+1]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j+1];
          mat_c[j+cols_b*(i+1)+2]=mat_c[j+cols_b*(i+1)+2]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j+2];
          mat_c[j+cols_b*(i+1)+3]=mat_c[j+cols_b*(i+1)+3]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j+3];
          mat_c[j+cols_b*(i+1)+4]=mat_c[j+cols_b*(i+1)+4]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j+4];
          mat_c[j+cols_b*(i+1)+5]=mat_c[j+cols_b*(i+1)+5]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j+5];
          mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*(i+2)+1]=mat_c[j+cols_b*(i+2)+1]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j+1];
          mat_c[j+cols_b*(i+2)+2]=mat_c[j+cols_b*(i+2)+2]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j+2];
          mat_c[j+cols_b*(i+2)+3]=mat_c[j+cols_b*(i+2)+3]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j+3];
          mat_c[j+cols_b*(i+2)+4]=mat_c[j+cols_b*(i+2)+4]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j+4];
          mat_c[j+cols_b*(i+2)+5]=mat_c[j+cols_b*(i+2)+5]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j+5];
        }
      }
      for (j=cols_b-((cols_b-(0))%6); j<=cols_b-1; j=j+1) {
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*(i+1)]=mat_c[j+cols_b*(i+1)]+mat_a[cols_a*(i+1)+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*(i+2)]=mat_c[j+cols_b*(i+2)]+mat_a[cols_a*(i+2)+k]*mat_b[cols_b*k+j];
        }
      }
    }
    for (i=rows_a-((rows_a-(0))%3); i<=rows_a-1; i=i+1) {
      int j;
      for (j=0; j<=cols_b-6; j=j+6) {
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
          mat_c[j+cols_b*i+1]=mat_c[j+cols_b*i+1]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+1];
          mat_c[j+cols_b*i+2]=mat_c[j+cols_b*i+2]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+2];
          mat_c[j+cols_b*i+3]=mat_c[j+cols_b*i+3]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+3];
          mat_c[j+cols_b*i+4]=mat_c[j+cols_b*i+4]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+4];
          mat_c[j+cols_b*i+5]=mat_c[j+cols_b*i+5]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j+5];
        }
      }
      for (j=cols_b-((cols_b-(0))%6); j<=cols_b-1; j=j+1) 
        for (k=0; k<=cols_a-1; k++ ) {
          mat_c[j+cols_b*i]=mat_c[j+cols_b*i]+mat_a[cols_a*i+k]*mat_b[cols_b*k+j];
        }
    }
  }
/*@ end @*/
/*@ end @*/
}
